import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>ChessELOle</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Guess the Lichess ELO of a random chess game and see how well you fare :D" />
        <meta name="keywords" content="Chess, Guess, Game, ELO, Rating, Score, ChessELOle, Lichess" />
        <meta name="author" content="RandomGamingDev" />
      </head>
      <body className={`dark:bg-neutral-900 bg-neutral-200 antialiased`}>
        {children}
      </body>
    </html>
  );
}
